### ISSUE TITLE
port scanner dont work!

### ISSUE THREAD

**Issue by ghost** [RiXxUkr/DDoS-master#2]
[ x ] IP / Domain 'google.com' is invalid or down!

[ x ] IP / Domain '213.24.76.23' is invalid or down!

[ x ] IP / Domain '188.128.102.66' is invalid or down!

it is my worked ip:
[ x ] IP / Domain '192.168.0.1' is invalid or down!

you kill my time!!!

**Comment by RiXxUkr** [comment]
To u understand I've spent around 5 mins to this created. If ur time worth so much for u - don't spent it on some shit like this.
